// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYMOnMgr0Uwz4XJysP8fB4AqWoeTXUvmQ',
    appId: '1:30343124835:android:05b595c98b90510baf2556',
    messagingSenderId: '30343124835',
    projectId: 'minimalchatapp-103c6',
    storageBucket: 'minimalchatapp-103c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRJ3lZd8nN4y-ld7wi8_ByC_3HI9Rzrnw',
    appId: '1:30343124835:ios:ab3a64a1c5e21687af2556',
    messagingSenderId: '30343124835',
    projectId: 'minimalchatapp-103c6',
    storageBucket: 'minimalchatapp-103c6.firebasestorage.app',
    iosBundleId: 'com.example.minimalchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRJ3lZd8nN4y-ld7wi8_ByC_3HI9Rzrnw',
    appId: '1:30343124835:ios:ab3a64a1c5e21687af2556',
    messagingSenderId: '30343124835',
    projectId: 'minimalchatapp-103c6',
    storageBucket: 'minimalchatapp-103c6.firebasestorage.app',
    iosBundleId: 'com.example.minimalchatapp',
  );
}